//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceOrion.QueryExchangeRate {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sap.com/xi/AP/Common/Global")]
    public partial class StandardFaultMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ExchangeFaultData standardField;
        
        private StandardFaultMessageExtension additionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ExchangeFaultData standard {
            get {
                return this.standardField;
            }
            set {
                this.standardField = value;
                this.RaisePropertyChanged("standard");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public StandardFaultMessageExtension addition {
            get {
                return this.additionField;
            }
            set {
                this.additionField = value;
                this.RaisePropertyChanged("addition");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/Global")]
    public partial class ExchangeFaultData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultTextField;
        
        private string faultUrlField;
        
        private ExchangeLogData[] faultDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultText {
            get {
                return this.faultTextField;
            }
            set {
                this.faultTextField = value;
                this.RaisePropertyChanged("faultText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultUrl {
            get {
                return this.faultUrlField;
            }
            set {
                this.faultUrlField = value;
                this.RaisePropertyChanged("faultUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("faultDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ExchangeLogData[] faultDetail {
            get {
                return this.faultDetailField;
            }
            set {
                this.faultDetailField = value;
                this.RaisePropertyChanged("faultDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/Global")]
    public partial class ExchangeLogData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string severityField;
        
        private string textField;
        
        private string urlField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/Global")]
    public partial class StandardFaultMessageExtension : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Log logField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Log Log {
            get {
                return this.logField;
            }
            set {
                this.logField = value;
                this.RaisePropertyChanged("Log");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class Log : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string businessDocumentProcessingResultCodeField;
        
        private string maximumLogItemSeverityCodeField;
        
        private LogItem[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string BusinessDocumentProcessingResultCode {
            get {
                return this.businessDocumentProcessingResultCodeField;
            }
            set {
                this.businessDocumentProcessingResultCodeField = value;
                this.RaisePropertyChanged("BusinessDocumentProcessingResultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string MaximumLogItemSeverityCode {
            get {
                return this.maximumLogItemSeverityCodeField;
            }
            set {
                this.maximumLogItemSeverityCodeField = value;
                this.RaisePropertyChanged("MaximumLogItemSeverityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public LogItem[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class LogItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeIDField;
        
        private LogItemCategoryCode categoryCodeField;
        
        private string severityCodeField;
        
        private string referenceObjectNodeSenderTechnicalIDField;
        
        private string referenceMessageElementNameField;
        
        private string noteField;
        
        private string noteTemplateTextField;
        
        private LogItemNotePlaceholderSubstitutionList logItemNotePlaceholderSubstitutionListField;
        
        private string webURIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string TypeID {
            get {
                return this.typeIDField;
            }
            set {
                this.typeIDField = value;
                this.RaisePropertyChanged("TypeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public LogItemCategoryCode CategoryCode {
            get {
                return this.categoryCodeField;
            }
            set {
                this.categoryCodeField = value;
                this.RaisePropertyChanged("CategoryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=2)]
        public string SeverityCode {
            get {
                return this.severityCodeField;
            }
            set {
                this.severityCodeField = value;
                this.RaisePropertyChanged("SeverityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=3)]
        public string ReferenceObjectNodeSenderTechnicalID {
            get {
                return this.referenceObjectNodeSenderTechnicalIDField;
            }
            set {
                this.referenceObjectNodeSenderTechnicalIDField = value;
                this.RaisePropertyChanged("ReferenceObjectNodeSenderTechnicalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ReferenceMessageElementName {
            get {
                return this.referenceMessageElementNameField;
            }
            set {
                this.referenceMessageElementNameField = value;
                this.RaisePropertyChanged("ReferenceMessageElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string NoteTemplateText {
            get {
                return this.noteTemplateTextField;
            }
            set {
                this.noteTemplateTextField = value;
                this.RaisePropertyChanged("NoteTemplateText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public LogItemNotePlaceholderSubstitutionList LogItemNotePlaceholderSubstitutionList {
            get {
                return this.logItemNotePlaceholderSubstitutionListField;
            }
            set {
                this.logItemNotePlaceholderSubstitutionListField = value;
                this.RaisePropertyChanged("LogItemNotePlaceholderSubstitutionList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=8)]
        public string WebURI {
            get {
                return this.webURIField;
            }
            set {
                this.webURIField = value;
                this.RaisePropertyChanged("WebURI");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class LogItemCategoryCode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string listIDField;
        
        private string listVersionIDField;
        
        private string listAgencyIDField;
        
        private string listAgencySchemeIDField;
        
        private AgencyIdentificationCode listAgencySchemeAgencyIDField;
        
        private bool listAgencySchemeAgencyIDFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listID {
            get {
                return this.listIDField;
            }
            set {
                this.listIDField = value;
                this.RaisePropertyChanged("listID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listVersionID {
            get {
                return this.listVersionIDField;
            }
            set {
                this.listVersionIDField = value;
                this.RaisePropertyChanged("listVersionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listAgencyID {
            get {
                return this.listAgencyIDField;
            }
            set {
                this.listAgencyIDField = value;
                this.RaisePropertyChanged("listAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listAgencySchemeID {
            get {
                return this.listAgencySchemeIDField;
            }
            set {
                this.listAgencySchemeIDField = value;
                this.RaisePropertyChanged("listAgencySchemeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AgencyIdentificationCode listAgencySchemeAgencyID {
            get {
                return this.listAgencySchemeAgencyIDField;
            }
            set {
                this.listAgencySchemeAgencyIDField = value;
                this.RaisePropertyChanged("listAgencySchemeAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listAgencySchemeAgencyIDSpecified {
            get {
                return this.listAgencySchemeAgencyIDFieldSpecified;
            }
            set {
                this.listAgencySchemeAgencyIDFieldSpecified = value;
                this.RaisePropertyChanged("listAgencySchemeAgencyIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/BASIS/Global")]
    public enum AgencyIdentificationCode {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("16")]
        Item16,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17")]
        Item17,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("84")]
        Item84,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("107")]
        Item107,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("109")]
        Item109,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("112")]
        Item112,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("113")]
        Item113,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("114")]
        Item114,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("116")]
        Item116,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("117")]
        Item117,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("124")]
        Item124,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("130")]
        Item130,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("131")]
        Item131,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("138")]
        Item138,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("142")]
        Item142,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("146")]
        Item146,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("262")]
        Item262,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("296")]
        Item296,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("310")]
        Item310,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class LogItemNotePlaceholderSubstitutionList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string firstPlaceholderIDField;
        
        private string secondPlaceholderIDField;
        
        private string thirdPlaceholderIDField;
        
        private string fourthPlaceholderIDField;
        
        private string firstPlaceholderSubstitutionTextField;
        
        private string secondPlaceholderSubstitutionTextField;
        
        private string thirdPlaceholderSubstitutionTextField;
        
        private string fourthPlaceholderSubstitutionTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string FirstPlaceholderID {
            get {
                return this.firstPlaceholderIDField;
            }
            set {
                this.firstPlaceholderIDField = value;
                this.RaisePropertyChanged("FirstPlaceholderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string SecondPlaceholderID {
            get {
                return this.secondPlaceholderIDField;
            }
            set {
                this.secondPlaceholderIDField = value;
                this.RaisePropertyChanged("SecondPlaceholderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=2)]
        public string ThirdPlaceholderID {
            get {
                return this.thirdPlaceholderIDField;
            }
            set {
                this.thirdPlaceholderIDField = value;
                this.RaisePropertyChanged("ThirdPlaceholderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=3)]
        public string FourthPlaceholderID {
            get {
                return this.fourthPlaceholderIDField;
            }
            set {
                this.fourthPlaceholderIDField = value;
                this.RaisePropertyChanged("FourthPlaceholderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string FirstPlaceholderSubstitutionText {
            get {
                return this.firstPlaceholderSubstitutionTextField;
            }
            set {
                this.firstPlaceholderSubstitutionTextField = value;
                this.RaisePropertyChanged("FirstPlaceholderSubstitutionText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SecondPlaceholderSubstitutionText {
            get {
                return this.secondPlaceholderSubstitutionTextField;
            }
            set {
                this.secondPlaceholderSubstitutionTextField = value;
                this.RaisePropertyChanged("SecondPlaceholderSubstitutionText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ThirdPlaceholderSubstitutionText {
            get {
                return this.thirdPlaceholderSubstitutionTextField;
            }
            set {
                this.thirdPlaceholderSubstitutionTextField = value;
                this.RaisePropertyChanged("ThirdPlaceholderSubstitutionText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string FourthPlaceholderSubstitutionText {
            get {
                return this.fourthPlaceholderSubstitutionTextField;
            }
            set {
                this.fourthPlaceholderSubstitutionTextField = value;
                this.RaisePropertyChanged("FourthPlaceholderSubstitutionText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class ResponseProcessingConditions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnedQueryHitsNumberValueField;
        
        private bool moreHitsAvailableIndicatorField;
        
        private ObjectID lastReturnedObjectIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int ReturnedQueryHitsNumberValue {
            get {
                return this.returnedQueryHitsNumberValueField;
            }
            set {
                this.returnedQueryHitsNumberValueField = value;
                this.RaisePropertyChanged("ReturnedQueryHitsNumberValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool MoreHitsAvailableIndicator {
            get {
                return this.moreHitsAvailableIndicatorField;
            }
            set {
                this.moreHitsAvailableIndicatorField = value;
                this.RaisePropertyChanged("MoreHitsAvailableIndicator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ObjectID LastReturnedObjectID {
            get {
                return this.lastReturnedObjectIDField;
            }
            set {
                this.lastReturnedObjectIDField = value;
                this.RaisePropertyChanged("LastReturnedObjectID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class ObjectID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string schemeIDField;
        
        private string schemeVersionIDField;
        
        private string schemeAgencyIDField;
        
        private string schemeAgencySchemeIDField;
        
        private AgencyIdentificationCode schemeAgencySchemeAgencyIDField;
        
        private bool schemeAgencySchemeAgencyIDFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
                this.RaisePropertyChanged("schemeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeVersionID {
            get {
                return this.schemeVersionIDField;
            }
            set {
                this.schemeVersionIDField = value;
                this.RaisePropertyChanged("schemeVersionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
                this.RaisePropertyChanged("schemeAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencySchemeID {
            get {
                return this.schemeAgencySchemeIDField;
            }
            set {
                this.schemeAgencySchemeIDField = value;
                this.RaisePropertyChanged("schemeAgencySchemeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AgencyIdentificationCode schemeAgencySchemeAgencyID {
            get {
                return this.schemeAgencySchemeAgencyIDField;
            }
            set {
                this.schemeAgencySchemeAgencyIDField = value;
                this.RaisePropertyChanged("schemeAgencySchemeAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schemeAgencySchemeAgencyIDSpecified {
            get {
                return this.schemeAgencySchemeAgencyIDFieldSpecified;
            }
            set {
                this.schemeAgencySchemeAgencyIDFieldSpecified = value;
                this.RaisePropertyChanged("schemeAgencySchemeAgencyIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class UUID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
                this.RaisePropertyChanged("schemeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
                this.RaisePropertyChanged("schemeAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/IS/CurrencyAndExchangeRates/Global")]
    public partial class ExchangeRateResponseExchangeRate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string changeStateIDField;
        
        private ExchangeRateTypeCode typeCodeField;
        
        private string sourceCurrencyCodeField;
        
        private string targetCurrencyCodeField;
        
        private UUID bidExchangeRateUUIDField;
        
        private UUID midExchangeRateUUIDField;
        
        private UUID askExchangeRateUUIDField;
        
        private decimal bidRateField;
        
        private bool bidRateFieldSpecified;
        
        private decimal midRateField;
        
        private bool midRateFieldSpecified;
        
        private decimal askRateField;
        
        private bool askRateFieldSpecified;
        
        private System.DateTime validFromDateTimeField;
        
        private bool validFromDateTimeFieldSpecified;
        
        private System.DateTime registerDateTimeField;
        
        private bool registerDateTimeFieldSpecified;
        
        private bool deletedIndicatorCodeField;
        
        private bool deletedIndicatorCodeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string ChangeStateID {
            get {
                return this.changeStateIDField;
            }
            set {
                this.changeStateIDField = value;
                this.RaisePropertyChanged("ChangeStateID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ExchangeRateTypeCode TypeCode {
            get {
                return this.typeCodeField;
            }
            set {
                this.typeCodeField = value;
                this.RaisePropertyChanged("TypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=2)]
        public string SourceCurrencyCode {
            get {
                return this.sourceCurrencyCodeField;
            }
            set {
                this.sourceCurrencyCodeField = value;
                this.RaisePropertyChanged("SourceCurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=3)]
        public string TargetCurrencyCode {
            get {
                return this.targetCurrencyCodeField;
            }
            set {
                this.targetCurrencyCodeField = value;
                this.RaisePropertyChanged("TargetCurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public UUID BidExchangeRateUUID {
            get {
                return this.bidExchangeRateUUIDField;
            }
            set {
                this.bidExchangeRateUUIDField = value;
                this.RaisePropertyChanged("BidExchangeRateUUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public UUID MidExchangeRateUUID {
            get {
                return this.midExchangeRateUUIDField;
            }
            set {
                this.midExchangeRateUUIDField = value;
                this.RaisePropertyChanged("MidExchangeRateUUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public UUID AskExchangeRateUUID {
            get {
                return this.askExchangeRateUUIDField;
            }
            set {
                this.askExchangeRateUUIDField = value;
                this.RaisePropertyChanged("AskExchangeRateUUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal BidRate {
            get {
                return this.bidRateField;
            }
            set {
                this.bidRateField = value;
                this.RaisePropertyChanged("BidRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BidRateSpecified {
            get {
                return this.bidRateFieldSpecified;
            }
            set {
                this.bidRateFieldSpecified = value;
                this.RaisePropertyChanged("BidRateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal MidRate {
            get {
                return this.midRateField;
            }
            set {
                this.midRateField = value;
                this.RaisePropertyChanged("MidRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MidRateSpecified {
            get {
                return this.midRateFieldSpecified;
            }
            set {
                this.midRateFieldSpecified = value;
                this.RaisePropertyChanged("MidRateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal AskRate {
            get {
                return this.askRateField;
            }
            set {
                this.askRateField = value;
                this.RaisePropertyChanged("AskRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AskRateSpecified {
            get {
                return this.askRateFieldSpecified;
            }
            set {
                this.askRateFieldSpecified = value;
                this.RaisePropertyChanged("AskRateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public System.DateTime ValidFromDateTime {
            get {
                return this.validFromDateTimeField;
            }
            set {
                this.validFromDateTimeField = value;
                this.RaisePropertyChanged("ValidFromDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidFromDateTimeSpecified {
            get {
                return this.validFromDateTimeFieldSpecified;
            }
            set {
                this.validFromDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("ValidFromDateTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public System.DateTime RegisterDateTime {
            get {
                return this.registerDateTimeField;
            }
            set {
                this.registerDateTimeField = value;
                this.RaisePropertyChanged("RegisterDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegisterDateTimeSpecified {
            get {
                return this.registerDateTimeFieldSpecified;
            }
            set {
                this.registerDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("RegisterDateTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public bool DeletedIndicatorCode {
            get {
                return this.deletedIndicatorCodeField;
            }
            set {
                this.deletedIndicatorCodeField = value;
                this.RaisePropertyChanged("DeletedIndicatorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeletedIndicatorCodeSpecified {
            get {
                return this.deletedIndicatorCodeFieldSpecified;
            }
            set {
                this.deletedIndicatorCodeFieldSpecified = value;
                this.RaisePropertyChanged("DeletedIndicatorCodeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class ExchangeRateTypeCode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string listIDField;
        
        private string listVersionIDField;
        
        private string listAgencyIDField;
        
        private string listAgencySchemeIDField;
        
        private AgencyIdentificationCode listAgencySchemeAgencyIDField;
        
        private bool listAgencySchemeAgencyIDFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listID {
            get {
                return this.listIDField;
            }
            set {
                this.listIDField = value;
                this.RaisePropertyChanged("listID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listVersionID {
            get {
                return this.listVersionIDField;
            }
            set {
                this.listVersionIDField = value;
                this.RaisePropertyChanged("listVersionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listAgencyID {
            get {
                return this.listAgencyIDField;
            }
            set {
                this.listAgencyIDField = value;
                this.RaisePropertyChanged("listAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listAgencySchemeID {
            get {
                return this.listAgencySchemeIDField;
            }
            set {
                this.listAgencySchemeIDField = value;
                this.RaisePropertyChanged("listAgencySchemeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AgencyIdentificationCode listAgencySchemeAgencyID {
            get {
                return this.listAgencySchemeAgencyIDField;
            }
            set {
                this.listAgencySchemeAgencyIDField = value;
                this.RaisePropertyChanged("listAgencySchemeAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listAgencySchemeAgencyIDSpecified {
            get {
                return this.listAgencySchemeAgencyIDFieldSpecified;
            }
            set {
                this.listAgencySchemeAgencyIDFieldSpecified = value;
                this.RaisePropertyChanged("listAgencySchemeAgencyIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/IS/CurrencyAndExchangeRates/Global")]
    public partial class ExchangeRateByElementsResponseMessage_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ExchangeRateResponseExchangeRate[] exchangeRateField;
        
        private ResponseProcessingConditions processingConditionsField;
        
        private Log logField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExchangeRate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ExchangeRateResponseExchangeRate[] ExchangeRate {
            get {
                return this.exchangeRateField;
            }
            set {
                this.exchangeRateField = value;
                this.RaisePropertyChanged("ExchangeRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ResponseProcessingConditions ProcessingConditions {
            get {
                return this.processingConditionsField;
            }
            set {
                this.processingConditionsField = value;
                this.RaisePropertyChanged("ProcessingConditions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Log Log {
            get {
                return this.logField;
            }
            set {
                this.logField = value;
                this.RaisePropertyChanged("Log");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class QueryProcessingConditions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int queryHitsMaximumNumberValueField;
        
        private bool queryHitsMaximumNumberValueFieldSpecified;
        
        private bool queryHitsUnlimitedIndicatorField;
        
        private ObjectID lastReturnedObjectIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int QueryHitsMaximumNumberValue {
            get {
                return this.queryHitsMaximumNumberValueField;
            }
            set {
                this.queryHitsMaximumNumberValueField = value;
                this.RaisePropertyChanged("QueryHitsMaximumNumberValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QueryHitsMaximumNumberValueSpecified {
            get {
                return this.queryHitsMaximumNumberValueFieldSpecified;
            }
            set {
                this.queryHitsMaximumNumberValueFieldSpecified = value;
                this.RaisePropertyChanged("QueryHitsMaximumNumberValueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool QueryHitsUnlimitedIndicator {
            get {
                return this.queryHitsUnlimitedIndicatorField;
            }
            set {
                this.queryHitsUnlimitedIndicatorField = value;
                this.RaisePropertyChanged("QueryHitsUnlimitedIndicator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ObjectID LastReturnedObjectID {
            get {
                return this.lastReturnedObjectIDField;
            }
            set {
                this.lastReturnedObjectIDField = value;
                this.RaisePropertyChanged("LastReturnedObjectID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/Global")]
    public partial class GLOBAL_SelectionByDateTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string inclusionExclusionCodeField;
        
        private string intervalBoundaryTypeCodeField;
        
        private System.DateTime lowerBoundaryDateTimeField;
        
        private bool lowerBoundaryDateTimeFieldSpecified;
        
        private System.DateTime upperBoundaryDateTimeField;
        
        private bool upperBoundaryDateTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string InclusionExclusionCode {
            get {
                return this.inclusionExclusionCodeField;
            }
            set {
                this.inclusionExclusionCodeField = value;
                this.RaisePropertyChanged("InclusionExclusionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string IntervalBoundaryTypeCode {
            get {
                return this.intervalBoundaryTypeCodeField;
            }
            set {
                this.intervalBoundaryTypeCodeField = value;
                this.RaisePropertyChanged("IntervalBoundaryTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime LowerBoundaryDateTime {
            get {
                return this.lowerBoundaryDateTimeField;
            }
            set {
                this.lowerBoundaryDateTimeField = value;
                this.RaisePropertyChanged("LowerBoundaryDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LowerBoundaryDateTimeSpecified {
            get {
                return this.lowerBoundaryDateTimeFieldSpecified;
            }
            set {
                this.lowerBoundaryDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("LowerBoundaryDateTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime UpperBoundaryDateTime {
            get {
                return this.upperBoundaryDateTimeField;
            }
            set {
                this.upperBoundaryDateTimeField = value;
                this.RaisePropertyChanged("UpperBoundaryDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UpperBoundaryDateTimeSpecified {
            get {
                return this.upperBoundaryDateTimeFieldSpecified;
            }
            set {
                this.upperBoundaryDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("UpperBoundaryDateTimeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/IS/CurrencyAndExchangeRates/Global")]
    public partial class ExchangeRateSelectionByCurrencyCode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string inclusionExclusionCodeField;
        
        private string intervalBoundaryTypeCodeField;
        
        private string lowerBoundaryCurrencyCodeField;
        
        private string upperBoundaryCurrencyCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string InclusionExclusionCode {
            get {
                return this.inclusionExclusionCodeField;
            }
            set {
                this.inclusionExclusionCodeField = value;
                this.RaisePropertyChanged("InclusionExclusionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string IntervalBoundaryTypeCode {
            get {
                return this.intervalBoundaryTypeCodeField;
            }
            set {
                this.intervalBoundaryTypeCodeField = value;
                this.RaisePropertyChanged("IntervalBoundaryTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=2)]
        public string LowerBoundaryCurrencyCode {
            get {
                return this.lowerBoundaryCurrencyCodeField;
            }
            set {
                this.lowerBoundaryCurrencyCodeField = value;
                this.RaisePropertyChanged("LowerBoundaryCurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=3)]
        public string UpperBoundaryCurrencyCode {
            get {
                return this.upperBoundaryCurrencyCodeField;
            }
            set {
                this.upperBoundaryCurrencyCodeField = value;
                this.RaisePropertyChanged("UpperBoundaryCurrencyCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/IS/CurrencyAndExchangeRates/Global")]
    public partial class ExchangeRateSelectionByTypeCode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string inclusionExclusionCodeField;
        
        private string intervalBoundaryTypeCodeField;
        
        private ExchangeRateTypeCode lowerBoundaryTypeCodeField;
        
        private ExchangeRateTypeCode upperBoundaryTypeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string InclusionExclusionCode {
            get {
                return this.inclusionExclusionCodeField;
            }
            set {
                this.inclusionExclusionCodeField = value;
                this.RaisePropertyChanged("InclusionExclusionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string IntervalBoundaryTypeCode {
            get {
                return this.intervalBoundaryTypeCodeField;
            }
            set {
                this.intervalBoundaryTypeCodeField = value;
                this.RaisePropertyChanged("IntervalBoundaryTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ExchangeRateTypeCode LowerBoundaryTypeCode {
            get {
                return this.lowerBoundaryTypeCodeField;
            }
            set {
                this.lowerBoundaryTypeCodeField = value;
                this.RaisePropertyChanged("LowerBoundaryTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ExchangeRateTypeCode UpperBoundaryTypeCode {
            get {
                return this.upperBoundaryTypeCodeField;
            }
            set {
                this.upperBoundaryTypeCodeField = value;
                this.RaisePropertyChanged("UpperBoundaryTypeCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/Global")]
    public partial class NOSC_SelectionByUUID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string inclusionExclusionCodeField;
        
        private string intervalBoundaryTypeCodeField;
        
        private string lowerBoundaryUUIDField;
        
        private string upperBoundaryUUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string InclusionExclusionCode {
            get {
                return this.inclusionExclusionCodeField;
            }
            set {
                this.inclusionExclusionCodeField = value;
                this.RaisePropertyChanged("InclusionExclusionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string IntervalBoundaryTypeCode {
            get {
                return this.intervalBoundaryTypeCodeField;
            }
            set {
                this.intervalBoundaryTypeCodeField = value;
                this.RaisePropertyChanged("IntervalBoundaryTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=2)]
        public string LowerBoundaryUUID {
            get {
                return this.lowerBoundaryUUIDField;
            }
            set {
                this.lowerBoundaryUUIDField = value;
                this.RaisePropertyChanged("LowerBoundaryUUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=3)]
        public string UpperBoundaryUUID {
            get {
                return this.upperBoundaryUUIDField;
            }
            set {
                this.upperBoundaryUUIDField = value;
                this.RaisePropertyChanged("UpperBoundaryUUID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/IS/CurrencyAndExchangeRates/Global")]
    public partial class ExchangeRateSelectionByElements : object, System.ComponentModel.INotifyPropertyChanged {
        
        private NOSC_SelectionByUUID[] selectionByUUIDField;
        
        private ExchangeRateSelectionByTypeCode[] selectionByTypeCodeField;
        
        private ExchangeRateSelectionByCurrencyCode[] selectionBySourceCurrencyCodeField;
        
        private ExchangeRateSelectionByCurrencyCode[] selectionByTargetCurrencyCodeField;
        
        private GLOBAL_SelectionByDateTime[] selectionByValidFromDateTimeField;
        
        private GLOBAL_SelectionByDateTime[] selectionByValidToDateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SelectionByUUID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public NOSC_SelectionByUUID[] SelectionByUUID {
            get {
                return this.selectionByUUIDField;
            }
            set {
                this.selectionByUUIDField = value;
                this.RaisePropertyChanged("SelectionByUUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SelectionByTypeCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ExchangeRateSelectionByTypeCode[] SelectionByTypeCode {
            get {
                return this.selectionByTypeCodeField;
            }
            set {
                this.selectionByTypeCodeField = value;
                this.RaisePropertyChanged("SelectionByTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SelectionBySourceCurrencyCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ExchangeRateSelectionByCurrencyCode[] SelectionBySourceCurrencyCode {
            get {
                return this.selectionBySourceCurrencyCodeField;
            }
            set {
                this.selectionBySourceCurrencyCodeField = value;
                this.RaisePropertyChanged("SelectionBySourceCurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SelectionByTargetCurrencyCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ExchangeRateSelectionByCurrencyCode[] SelectionByTargetCurrencyCode {
            get {
                return this.selectionByTargetCurrencyCodeField;
            }
            set {
                this.selectionByTargetCurrencyCodeField = value;
                this.RaisePropertyChanged("SelectionByTargetCurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SelectionByValidFromDateTime", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public GLOBAL_SelectionByDateTime[] SelectionByValidFromDateTime {
            get {
                return this.selectionByValidFromDateTimeField;
            }
            set {
                this.selectionByValidFromDateTimeField = value;
                this.RaisePropertyChanged("SelectionByValidFromDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SelectionByValidToDateTime", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public GLOBAL_SelectionByDateTime[] SelectionByValidToDateTime {
            get {
                return this.selectionByValidToDateTimeField;
            }
            set {
                this.selectionByValidToDateTimeField = value;
                this.RaisePropertyChanged("SelectionByValidToDateTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/IS/CurrencyAndExchangeRates/Global")]
    public partial class ExchangeRateByElementsQueryMessage_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ExchangeRateSelectionByElements exchangeRateSelectionByElementsField;
        
        private QueryProcessingConditions processingConditionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ExchangeRateSelectionByElements ExchangeRateSelectionByElements {
            get {
                return this.exchangeRateSelectionByElementsField;
            }
            set {
                this.exchangeRateSelectionByElementsField = value;
                this.RaisePropertyChanged("ExchangeRateSelectionByElements");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public QueryProcessingConditions ProcessingConditions {
            get {
                return this.processingConditionsField;
            }
            set {
                this.processingConditionsField = value;
                this.RaisePropertyChanged("ProcessingConditions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sap.com/xi/AP/IS/CurrencyAndExchangeRates/Global", ConfigurationName="QueryExchangeRate.QueryExchangeRateIn_V1")]
    public interface QueryExchangeRateIn_V1 {
        
        // CODEGEN: Generating message contract since the operation FindByElements is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/AP/IS/CurrencyAndExchangeRates/Global/QueryExchangeRateIn_V1/Fi" +
            "ndByElementsRequest", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceOrion.QueryExchangeRate.StandardFaultMessage), Action="http://sap.com/xi/AP/IS/CurrencyAndExchangeRates/Global/QueryExchangeRateIn_V1/Fi" +
            "ndByElementsRequest", Name="StandardFaultMessage", Namespace="http://sap.com/xi/AP/Common/Global")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceOrion.QueryExchangeRate.FindByElementsResponse FindByElements(ServiceOrion.QueryExchangeRate.FindByElementsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/AP/IS/CurrencyAndExchangeRates/Global/QueryExchangeRateIn_V1/Fi" +
            "ndByElementsRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceOrion.QueryExchangeRate.FindByElementsResponse> FindByElementsAsync(ServiceOrion.QueryExchangeRate.FindByElementsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindByElementsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sap.com/xi/SAPGlobal20/Global", Order=0)]
        public ServiceOrion.QueryExchangeRate.ExchangeRateByElementsQueryMessage_sync ExchangeRateByElementsQuery_sync;
        
        public FindByElementsRequest() {
        }
        
        public FindByElementsRequest(ServiceOrion.QueryExchangeRate.ExchangeRateByElementsQueryMessage_sync ExchangeRateByElementsQuery_sync) {
            this.ExchangeRateByElementsQuery_sync = ExchangeRateByElementsQuery_sync;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindByElementsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sap.com/xi/SAPGlobal20/Global", Order=0)]
        public ServiceOrion.QueryExchangeRate.ExchangeRateByElementsResponseMessage_sync ExchangeRateByElementsResponse_sync;
        
        public FindByElementsResponse() {
        }
        
        public FindByElementsResponse(ServiceOrion.QueryExchangeRate.ExchangeRateByElementsResponseMessage_sync ExchangeRateByElementsResponse_sync) {
            this.ExchangeRateByElementsResponse_sync = ExchangeRateByElementsResponse_sync;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QueryExchangeRateIn_V1Channel : ServiceOrion.QueryExchangeRate.QueryExchangeRateIn_V1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryExchangeRateIn_V1Client : System.ServiceModel.ClientBase<ServiceOrion.QueryExchangeRate.QueryExchangeRateIn_V1>, ServiceOrion.QueryExchangeRate.QueryExchangeRateIn_V1 {
        
        public QueryExchangeRateIn_V1Client() {
        }
        
        public QueryExchangeRateIn_V1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryExchangeRateIn_V1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryExchangeRateIn_V1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryExchangeRateIn_V1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceOrion.QueryExchangeRate.FindByElementsResponse ServiceOrion.QueryExchangeRate.QueryExchangeRateIn_V1.FindByElements(ServiceOrion.QueryExchangeRate.FindByElementsRequest request) {
            return base.Channel.FindByElements(request);
        }
        
        public ServiceOrion.QueryExchangeRate.ExchangeRateByElementsResponseMessage_sync FindByElements(ServiceOrion.QueryExchangeRate.ExchangeRateByElementsQueryMessage_sync ExchangeRateByElementsQuery_sync) {
            ServiceOrion.QueryExchangeRate.FindByElementsRequest inValue = new ServiceOrion.QueryExchangeRate.FindByElementsRequest();
            inValue.ExchangeRateByElementsQuery_sync = ExchangeRateByElementsQuery_sync;
            ServiceOrion.QueryExchangeRate.FindByElementsResponse retVal = ((ServiceOrion.QueryExchangeRate.QueryExchangeRateIn_V1)(this)).FindByElements(inValue);
            return retVal.ExchangeRateByElementsResponse_sync;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceOrion.QueryExchangeRate.FindByElementsResponse> ServiceOrion.QueryExchangeRate.QueryExchangeRateIn_V1.FindByElementsAsync(ServiceOrion.QueryExchangeRate.FindByElementsRequest request) {
            return base.Channel.FindByElementsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceOrion.QueryExchangeRate.FindByElementsResponse> FindByElementsAsync(ServiceOrion.QueryExchangeRate.ExchangeRateByElementsQueryMessage_sync ExchangeRateByElementsQuery_sync) {
            ServiceOrion.QueryExchangeRate.FindByElementsRequest inValue = new ServiceOrion.QueryExchangeRate.FindByElementsRequest();
            inValue.ExchangeRateByElementsQuery_sync = ExchangeRateByElementsQuery_sync;
            return ((ServiceOrion.QueryExchangeRate.QueryExchangeRateIn_V1)(this)).FindByElementsAsync(inValue);
        }
    }
}
